# Generated by Django 4.2.26 on 2025-11-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudSignConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='CloudSign API Client ID', max_length=255, unique=True)),
                ('api_base_url', models.URLField(default='https://api-sandbox.cloudsign.jp', help_text='CloudSign API Base URL (e.g., https://api-sandbox.cloudsign.jp)')),
            ],
            options={
                'verbose_name': 'CloudSign Configuration',
                'verbose_name_plural': 'CloudSign Configuration',
            },
        ),
    ]
