# Generated by Django 4.2.5 on 2025-11-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_cloudsignconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='金額', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='customer_info',
            field=models.TextField(blank=True, help_text='取引先情報', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, help_text='期日', null=True),
        ),
    ]
