# Generated by Django 4.2.27 on 2025-12-31 23:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_cloudsign_document_id_contractfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudsignconfig',
            options={'verbose_name': 'CloudSign 設定', 'verbose_name_plural': 'CloudSign 設定'},
        ),
        migrations.AlterModelOptions(
            name='contractfile',
            options={'verbose_name': '契約書ファイル', 'verbose_name_plural': '契約書ファイル'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': '案件', 'verbose_name_plural': '案件'},
        ),
        migrations.AlterField(
            model_name='cloudsignconfig',
            name='api_base_url',
            field=models.URLField(default='https://api-sandbox.cloudsign.jp', help_text='CloudSign API Base URL (e.g., https://api-sandbox.cloudsign.jp)', verbose_name='APIベースURL'),
        ),
        migrations.AlterField(
            model_name='cloudsignconfig',
            name='client_id',
            field=models.CharField(help_text='CloudSign API Client ID', max_length=255, unique=True, verbose_name='クライアントID'),
        ),
        migrations.AlterField(
            model_name='contractfile',
            name='file',
            field=models.FileField(upload_to='contracts/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), projects.models.validate_file_size], verbose_name='契約書ファイル'),
        ),
        migrations.AlterField(
            model_name='contractfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project', verbose_name='案件'),
        ),
        migrations.AlterField(
            model_name='contractfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時'),
        ),
        migrations.AlterField(
            model_name='project',
            name='amount',
            field=models.BigIntegerField(blank=True, help_text='金額', null=True, verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cloudsign_document_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CloudSign Document ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer_info',
            field=models.TextField(blank=True, help_text='取引先情報', null=True, verbose_name='取引先情報'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='案件概要'),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, help_text='期日', null=True, verbose_name='期日'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='案件名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
