# Generated by Django 4.2.27 on 2026-01-01 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_cloudsignconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='宛先名')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='順序')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='projects.project', verbose_name='案件')),
            ],
            options={
                'verbose_name': '宛先',
                'verbose_name_plural': '宛先',
                'ordering': ['order', 'name'],
            },
        ),
    ]
