# Generated by Django 4.2.5 on 2026-01-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='cloudsign_participant_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CloudSign Participant ID'),
        ),
        migrations.AddField(
            model_name='participant',
            name='recipient_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='CloudSign Recipient ID for Embedded Signing'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='順序'),
        ),
    ]
