# Generated by Django 4.2.27 on 2026-01-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_participant_cloudsign_participant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_embedded_signer',
            field=models.BooleanField(default=False, verbose_name='組み込み署名者'),
        ),
        migrations.AddField(
            model_name='participant',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号'),
        ),
    ]
