# Generated by Django 4.2.27 on 2026-02-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_participant_callback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractfile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='元ファイル名'),
        ),
    ]
