# Generated by Django 4.2.27 on 2026-01-17 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_participant_is_embedded_signer_participant_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='signing_url',
            field=models.URLField(blank=True, null=True, verbose_name='署名URL'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
