# Generated by Django 4.2.27 on 2026-02-27 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_contractfile_original_name'),
        ('projects', '0010_alter_participant_email'),
    ]

    operations = [
    ]
